import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import '../providers/auth_provider.dart';
import '../providers/sick_leave_provider.dart';
import 'dashboard_screen.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  String? _generatedReason;
  bool _isGenerating = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _loadData();
    });
  }

  void _loadData() {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final sickLeaveProvider = Provider.of<SickLeaveProvider>(
      context,
      listen: false,
    );

    if (authProvider.user != null) {
      sickLeaveProvider.loadUserSickLeaves(authProvider.user!.uid);
      sickLeaveProvider.loadReasons();
    }
  }

  Future<void> _generateReason() async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final sickLeaveProvider = Provider.of<SickLeaveProvider>(
      context,
      listen: false,
    );

    if (authProvider.user == null) return;

    setState(() {
      _isGenerating = true;
    });

    try {
      final reason = await sickLeaveProvider.generateRandomReason(
        authProvider.user!.uid,
      );
      setState(() {
        _generatedReason = reason;
      });
    } finally {
      setState(() {
        _isGenerating = false;
      });
    }
  }

  Future<void> _useSickLeave() async {
    if (_generatedReason == null) return;

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final sickLeaveProvider = Provider.of<SickLeaveProvider>(
      context,
      listen: false,
    );

    if (authProvider.user == null) return;

    await sickLeaveProvider.addSickLeave(
      authProvider.user!.uid,
      _generatedReason!,
    );

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Sick leave recorded successfully!'),
          backgroundColor: Colors.green,
        ),
      );

      setState(() {
        _generatedReason = null;
      });
    }
  }

  void _shareReason() {
    if (_generatedReason != null) {
      Share.share(
        'Hi, I won\'t be able to come to work today because: $_generatedReason\n\nGenerated by SickBall app',
        subject: 'Sick Leave Notice',
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blue[50],
      appBar: AppBar(
        title: const Text('SickBall'),
        backgroundColor: Colors.blue[600],
        foregroundColor: Colors.white,
        elevation: 0,
        actions: [
          IconButton(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder:
                      (context) => MultiProvider(
                        providers: [
                          ChangeNotifierProvider.value(
                            value: Provider.of<AuthProvider>(
                              context,
                              listen: false,
                            ),
                          ),
                          ChangeNotifierProvider.value(
                            value: Provider.of<SickLeaveProvider>(
                              context,
                              listen: false,
                            ),
                          ),
                        ],
                        child: const DashboardScreen(),
                      ),
                ),
              );
            },
            icon: const Icon(Icons.dashboard),
          ),
          PopupMenuButton<String>(
            onSelected: (value) {
              if (value == 'logout') {
                Provider.of<AuthProvider>(context, listen: false).signOut();
              }
            },
            itemBuilder:
                (BuildContext context) => [
                  const PopupMenuItem<String>(
                    value: 'logout',
                    child: Row(
                      children: [
                        Icon(Icons.logout, size: 20),
                        SizedBox(width: 8),
                        Text('Logout'),
                      ],
                    ),
                  ),
                ],
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            // Welcome Card
            Consumer<AuthProvider>(
              builder: (context, authProvider, child) {
                return Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [Colors.blue[600]!, Colors.blue[400]!],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: BorderRadius.circular(16),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.blue.withOpacity(0.3),
                        blurRadius: 10,
                        offset: const Offset(0, 5),
                      ),
                    ],
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Welcome back!',
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      Text(
                        authProvider.userModel?.name ?? 'User',
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 24,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Consumer<SickLeaveProvider>(
                        builder: (context, sickLeaveProvider, child) {
                          final thisMonth = sickLeaveProvider
                              .getSickLeavesThisMonth(
                                authProvider.user?.uid ?? '',
                              );
                          return Text(
                            'Sick days this month: $thisMonth',
                            style: const TextStyle(
                              color: Colors.white70,
                              fontSize: 14,
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                );
              },
            ),
            const SizedBox(height: 24),

            // Generate Reason Card
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(16),
                boxShadow: [
                  BoxShadow(
                    color: Colors.grey.withOpacity(0.1),
                    blurRadius: 10,
                    offset: const Offset(0, 5),
                  ),
                ],
              ),
              child: Column(
                children: [
                  Icon(Icons.psychology, size: 48, color: Colors.purple[400]),
                  const SizedBox(height: 16),
                  Text(
                    'Generate Sick Leave Reason',
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Colors.grey[800],
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Get a creative and believable reason for your sick leave',
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 14, color: Colors.grey[600]),
                  ),
                  const SizedBox(height: 20),

                  // Generated Reason Display
                  if (_generatedReason != null)
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(16),
                      margin: const EdgeInsets.only(bottom: 16),
                      decoration: BoxDecoration(
                        color: Colors.green[50],
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: Colors.green[200]!),
                      ),
                      child: Text(
                        _generatedReason!,
                        style: TextStyle(
                          fontSize: 16,
                          color: Colors.green[800],
                          height: 1.4,
                        ),
                      ),
                    ),

                  // Generate Button
                  SizedBox(
                    width: double.infinity,
                    height: 48,
                    child: ElevatedButton(
                      onPressed: _isGenerating ? null : _generateReason,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.purple[400],
                        foregroundColor: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                      ),
                      child:
                          _isGenerating
                              ? const SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  valueColor: AlwaysStoppedAnimation<Color>(
                                    Colors.white,
                                  ),
                                ),
                              )
                              : Row(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  const Icon(Icons.refresh, size: 20),
                                  const SizedBox(width: 8),
                                  Text(
                                    _generatedReason == null
                                        ? 'Generate Reason'
                                        : 'Generate New Reason',
                                  ),
                                ],
                              ),
                    ),
                  ),

                  // Action Buttons
                  if (_generatedReason != null) ...[
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton(
                            onPressed: _shareReason,
                            style: OutlinedButton.styleFrom(
                              foregroundColor: Colors.blue[600],
                              side: BorderSide(color: Colors.blue[600]!),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: const Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(Icons.share, size: 16),
                                SizedBox(width: 6),
                                Text('Share'),
                              ],
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: ElevatedButton(
                            onPressed: _useSickLeave,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.green[600],
                              foregroundColor: Colors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: const Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(Icons.check, size: 16),
                                SizedBox(width: 6),
                                Text('Use This'),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ],
              ),
            ),
            const SizedBox(height: 24),

            // Quick Stats Card
            Consumer<SickLeaveProvider>(
              builder: (context, sickLeaveProvider, child) {
                return Consumer<AuthProvider>(
                  builder: (context, authProvider, child) {
                    final thisMonth = sickLeaveProvider.getSickLeavesThisMonth(
                      authProvider.user?.uid ?? '',
                    );
                    final thisYear = sickLeaveProvider.getSickLeavesThisYear(
                      authProvider.user?.uid ?? '',
                    );
                    final total = authProvider.userModel?.totalSickDays ?? 0;

                    return Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(16),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.grey.withOpacity(0.1),
                            blurRadius: 10,
                            offset: const Offset(0, 5),
                          ),
                        ],
                      ),
                      child: Column(
                        children: [
                          Text(
                            'Quick Stats',
                            style: TextStyle(
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                              color: Colors.grey[800],
                            ),
                          ),
                          const SizedBox(height: 16),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                            children: [
                              _buildStatItem(
                                'This Month',
                                thisMonth.toString(),
                                Colors.blue,
                              ),
                              _buildStatItem(
                                'This Year',
                                thisYear.toString(),
                                Colors.orange,
                              ),
                              _buildStatItem(
                                'Total',
                                total.toString(),
                                Colors.purple,
                              ),
                            ],
                          ),
                        ],
                      ),
                    );
                  },
                );
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStatItem(String label, String value, Color? color) {
    return Column(
      children: [
        Container(
          width: 50,
          height: 50,
          decoration: BoxDecoration(
            color: color?.withOpacity(0.1),
            shape: BoxShape.circle,
          ),
          child: Center(
            child: Text(
              value,
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: color,
              ),
            ),
          ),
        ),
        const SizedBox(height: 8),
        Text(label, style: TextStyle(fontSize: 12, color: Colors.grey[600])),
      ],
    );
  }
}
